FROM python

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY .server/ .server/
COPY .server/run.sh .

RUN chmod +x .server/run.sh

CMD [".server/run.sh"]
